### ISSUE TITLE
Hi,guys!

### ISSUE THREAD

**Issue by xqtr123** [luyu-fan/soccer-tractical#2]
Can you provide me with the code for the server-side processing of the football analysis system, I would like to learn it.

**Comment by luyu-fan** [comment]
Hi, I am so honored that you noticed my work,  but I can not provide you the server-side, because I have been graduated this summer and all the work and results have been handed over to the laboratory. so sorry.

**Comment by xqtr123** [comment]
It's okay, thank you very much for your reply.

**Comment by xqtr123** [comment]
It's okay, thank you very much for your reply！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "luyu-fan/soccer-tractical"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月14日(星期四) 晚上8:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [luyu-fan/soccer-tractical] Hi,guys! (Issue #2)





 
Hi, I am so honored that you noticed my work,  but I can not provide you the server-side, because I have been graduated this summer and all the work and results have been handed over to the laboratory. so sorry.
